# Generated by Django 5.2.14 on 2026-06-02 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='availability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='doctors.doctorprofile'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.specialty'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['doctor', 'date'], name='doctors_ava_doctor__645d56_idx'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['is_booked'], name='doctors_ava_is_book_eb1a84_idx'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='end_after_start'),
        ),
    ]
