# Generated by Django 5.2.14 on 2026-06-03 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_public_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='DoctorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('public_id', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('CLINIC', 'Clinic'), ('CERTIFICATE', 'Certificate')], max_length=20)),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='doctors.doctorprofile')),
            ],
            options={
                'db_table': 'doctors_doctorimage',
                'ordering': ['kind', 'order', 'created_at'],
            },
        ),
    ]
