# Generated by Django 5.2.14 on 2026-06-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctorprofile_profile_public_id_doctorimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Consultation price for this slot in local currency.', max_digits=8, null=True),
        ),
    ]
